name: Run Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Install Packages
        run: yarn install
      - name: Run ESLint
        run: yarn lint
      - name: Run Unit Tests
        run: yarn test
  bundle:
    name: Create Archive
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Transpile Code
        run: yarn build
      - name: Archive Package
        uses: actions/upload-artifact@master
        with:
          name: archive
          path: dist
